### PR TITLE
PDF cleanup: hide `λ where` syntax

### PR DESCRIPTION
**Pull request by williamdemeo**
# Description

This addresses one item of issue #282.

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/CONTRIBUTING.md)
- [X] Self-reviewed the diff

### CODE REVIEW

**Review by WhatisRT — CHANGES_REQUESTED** [review]
In general I like this, but in this form it destroys alignment & has bad spacing. This is probably best fixed using `AgdaMultiCode` environments.

**Comment by williamdemeo** [comment]
I've added `AgdaMulticode` environment where needed.

In one case I change `AgdaAlign` to `AgdaMulticode`, to suppress extra line spacing that would have resulted from the addition of `\begin{code}[hide]...\end{code}` blocks.

**Comment by WhatisRT** [comment]
If you look at the PDF, you'll see that alignment & spacing are still broken in `Ratify` and `UTXOW`.

**Comment by williamdemeo** [comment]
I fixed the alignment in `Ledger.Ratify` and `Ledger.Utxow`.

Incidentally, the alignment of the union symbols in Fig 39 looks very strange to me.  Also, when did we start putting `=` on a new line.

Imho, the following code

```agda
actualVotes : RatifyEnv → PParams → CCData → GovAction
            → (GovRole × Credential ⇀ Vote) → (VDeleg ⇀ Vote)
actualVotes Γ pparams cc ga votes
  = mapKeys (credVoter CC) (actualCCVotes cc) ∪ˡ actualPDRepVotes ga
  ∪ˡ actualDRepVotes                          ∪ˡ actualSPOVotes ga
```

should be as either

```agda
actualVotes : RatifyEnv → PParams → CCData → GovAction
            → (GovRole × Credential ⇀ Vote) → (VDeleg ⇀ Vote)
actualVotes Γ pparams cc ga votes =
  mapKeys (credVoter CC) (actualCCVotes cc) 
  ∪ˡ actualPDRepVotes ga ∪ˡ actualDRepVotes ∪ˡ actualSPOVotes ga
```

or

```agda
actualVotes : RatifyEnv → PParams → CCData → GovAction
            → (GovRole × Credential ⇀ Vote) → (VDeleg ⇀ Vote)
actualVotes Γ pparams cc ga votes =
  mapKeys (credVoter CC) (actualCCVotes cc) ∪ˡ actualPDRepVotes ga 
  ∪ˡ actualDRepVotes ∪ˡ actualSPOVotes ga
```

**Pull request merged**
